### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by oubiwann** [clojusc/reggae#2]
Last release was in June. July had several updates, and there have been a few more since then.

Also: publish to Clojars when done.

**Comment by bjorstrom** [comment]
This will need a version bump. Recommend going to 0.2.0-SNAPSHOT instead of 0.1.3-SNAPSHOT ...

**Comment by oubiwann** [comment]
Ended up with 0.1.3-SNAPSHOT.

I've got some API updates/changes in mind -- let's do 0.2.0 after that.
